### ISSUE TITLE
My Servers & All Servers toggle button

### ISSUE THREAD

**Issue by DiamondDom** [wisp-gg/frontend#430] opened 2023-10-28 19:04 UTC
### Describe the feature and why you would like to see it.

My Servers & All Servers toggle button

### Describe the solution you'd like.

for a button to be added.

### Optional additional context to this request.

its in default PT Panel so i think it should be a great feature for wisp

**Comment by Software-Noob** [comment] 2023-10-28 19:06
Duplicate of #121

**Closed by Software-Noob** 2023-10-28 19:06 UTC
