### ISSUE TITLE
Minecraft Server Configuration Manager

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/frontend#398] opened 2023-04-25 08:01 UTC
### Describe the feature and why you would like to see it.

Adding a visual interface for managing Minecraft server configurations would make it easier for users to customize their server settings.

### Describe the solution you'd like.

Add an option in the server settings panel that allows users to edit server configuration files (bungeeconfig, server properties) and manage players.

**Comment by Software-Noob** [comment] 2023-10-21 06:52
Duplicate of #348

**Closed by Software-Noob** 2023-10-21 06:52 UTC
