### ISSUE TITLE
Regular Support Op - SFTP Access & Forced Log Out

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#354] opened 2022-12-11 23:54 UTC
### Describe the bug

The primary issue is with regular support op _(support op bypass disabled)_ not granting your account access to the SFTP of a Client Server. Support Op has been toggled and accessible. Support Op Bypass does not experience this issue.

A secondary issue, is that when updating the user permissions to grant support op, the user is logged out and their password is invalidated. Enabling and disabling Support Op Bypass trigger this issue as well.

### Expected Behavior

When support op access has been enabled on a server, the support operator's account will also have access to use the SFTP Server.

When updating the user permissions to assign Support Op role and/or apply Support Op Bypass, you are not forcefully logged out and your password no longer works.

### Actual Behavior

Support Op experiences the following FileZilla error, aka not authorized.

 ``` Status:	Access denied 
Error:	Authentication failed.
Error:	Critical error: Could not connect to server```

When changing the user permissions to assign Support Op and/or include Support Op Bypass in another request, you are kicked out of the panel and forced to manually reset your password.

### Steps to Reproduce

Step 1 - Have a regular user Panel Account & Login to the account.
Step 2 - Update User's Panel Account to become a Support Op.
Step 3 - Notice that you get hit with the error "Something went wrong while trying to perform this action." and see the "Unauthenticated" response in the Dev Tools console.
Step 4 - Refresh the page - You'll be logged out.
Step 5 - Attempt to use the password of the new support op. It'll fail with "The credentials provided do not match those we have on record. If you're not sure that your password is correct, try resetting it."
Step 6 - Force set the password through Admin.
Step 7 - You'll gain access again.
Step 8 - Try using credentials to access the SFTP of a Support Op enabled server.
Step 9 - You'll see your credentials don't work.
Step 10 - Cry.

### Browser Details

Chrome 108

### Operating System

Windows 10

### Optional additional information

_No response_

**Comment by Software-Noob** [comment] 2023-09-27 13:56
This issue is caused by #415 as the password is updated. Closing this in favor of the actual cause

**Closed** 2023-09-27 13:56 UTC
Labels: bug
