### ISSUE TITLE
You do not have permission to access the websocket for this server.

### ISSUE THREAD

**Issue by josua27176** [wisp-gg/frontend#46] opened 2022-02-13 16:35 UTC
**Describe the bug**
When going into a server as an administator then going back and trying to go into another server it comes up with "You do not have permission to access the websocket for this server." To fix it you just have to refresh the page but its quite annoying to have to do it every time I wanna switch to managing another server.

**To Reproduce**
1. Go to 'My Servers'
2. Click on a Server
3. Click on the logo at the top left
4. Click on another server it wont let you see console, or do anything like start stop or restart.

**Expected behavior**
I should be able to switch between servers without a problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/1637958/153762998-71dfa2ee-0eaa-4bff-8509-836efdf36864.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version 83.0

**Comment by WISPdotGG** [comment] 2022-02-13 16:38
Duplicate of #9

**Closed by WISPdotGG** 2022-02-13 16:38 UTC
