### ISSUE TITLE
Space At Bottom

### ISSUE THREAD

**Issue by HaloFloof** [wisp-gg/frontend#24] opened 2022-02-13 15:31 UTC
**Describe the bug**
There should probably be a space at the bottom, it looks super weird and was 99% a mistake.

**To Reproduce**
Just look here:
![image](https://user-images.githubusercontent.com/65753577/153760402-003edb66-6605-49a2-9df4-bc7b4052dd56.png)

**Expected behavior**
Well, there should be a space at the bottom..

**Screenshots**
![image](https://user-images.githubusercontent.com/65753577/153760416-a51f799b-54d2-47e5-b7fb-af30fcf09d6d.png)

**Desktop**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 22

**Additional context**
I think it's self explanatory. Might be caching, but who knows.

**Comment by WISPdotGG** [comment] 2022-02-13 15:31
Duplicate of #3

**Comment by WISPdotGG** [comment] 2022-02-13 15:33
Duplicate of #5

**Comment by WISPdotGG** [comment] 2022-02-13 15:41
/

**Closed by WISPdotGG** 2022-02-13 15:41 UTC

**Comment by WISPdotGG** [comment] 2022-02-13 15:45
Duplicate of #7
