### ISSUE TITLE
Dashboard page title

### ISSUE THREAD

**Issue by bgbuddyboy** [wisp-gg/frontend#114] opened 2022-02-14 05:48 UTC
**Describe the bug**
The dashboard page title is <company name> | navigation.index.title

**To Reproduce**
Go to dashboard of the panel.
Look at page title

**Expected behavior**
Not show navigation.index.title. Assuming it should be "dashboard" or similar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX
 - Version N/A

**Additional context**
N/A

**Comment by TrixterTheTux** [comment] 2022-02-14 06:13
Duplicate of https://github.com/wisp-gg/frontend/issues/49

**Closed by TrixterTheTux** 2022-02-14 06:13 UTC
