### ISSUE TITLE
Console accesable while server is suspended

### ISSUE THREAD

**Issue by krenny** [wisp-gg/frontend#95] opened 2022-02-13 20:33 UTC
**Describe the bug**
All "Toggle XX status" doesn't seem to work.

**To Reproduce**
1. Go to the admin area.
2. Click on 'Management>Servers'
3. Click on one Server.
4. Go to "Advanced"
5. Click on "Toggle" at the "Install Status" box
6. Go to the user area and find the server.
7. See that the status hasn't changed

**Expected behavior**
The status should be changed to Installation.

**Additional context**

Network tab of my browsers shows that it returns a 200 http code so the communication seems to work however the status don't change and there is no error or success message

**Comment by WISPdotGG** [comment] 2022-02-13 21:02
Interestingly, if the server is running the dot appears to show as installing, but the server is still accessible 
![image](https://user-images.githubusercontent.com/72014066/153774919-198546bc-0b25-4d84-bf7e-786943d3c360.png)

**Comment by victiondev** [comment] 2022-02-13 22:24
The stats endpoint used on the list page caches for a little while - it probably works but is still showing the old state temporarily. Updating/clearing the cache when the state is changed will be looked into

**Comment by krenny** [comment] 2022-02-13 22:31
Can confirm after some time and CTRL+F5 it shows correctly

However like mentioned above 

> Interestingly, if the server is running the dot appears to show as installing, but the server is still accessible ![image](https://user-images.githubusercontent.com/72014066/153774919-198546bc-0b25-4d84-bf7e-786943d3c360.png)

I can still access the server and even start it ( As root user though).
however trying to change tab(like filemanger) doesn't work.

renaming issue

**Comment by TrixterTheTux** [comment] 2022-02-15 20:40
I suspect this is caused by the same cause as #9 - should be fixed either way in the next release.

**Closed by TrixterTheTux** 2022-02-15 20:40 UTC
Labels: bug, medium
