### ISSUE TITLE
Possible to upload thing overpassing the disk limit. 

### ISSUE THREAD

**Issue by joti-prime** [wisp-gg/frontend#409] opened 2023-05-11 13:51 UTC
### Describe the bug

The disk limit only means that you cannot turn on the server but you can continue uploading files, this means that I can be using 1TB of space and have a limit of 1MB, the server will not turn on but I will be able to annoy.

### Expected Behavior

It would have to do like the pterodactyl panel, that before uploading a file it would calculate the space and if it exceeded it, it would not let you upload the file.

### Actual Behavior

Allowing to kill a server uploading things without limit. 

### Steps to Reproduce

Just upload files. 

### Browser Details

chrome (all)

### Operating System

windows (all)

### Optional additional information

```bash
Solve it is important.
```

**Comment by larsjarred9** [comment] 2023-06-05 10:18
Hi there,

This issue seems like an awesome issue to tackle as part of my college curriculum. I would like to tackle this issue.

I suppose the easiest step would be to check the file size and compare that to the available disk limit as @Joti-prime has mentioned before.

I look forward to receive some input on the matter.

**Comment by Software-Noob** [comment] 2023-07-07 18:52
Duplicate of #375

**Closed** 2023-08-19 10:23 UTC
Labels: bug
