### ISSUE TITLE
Strange scrollbar

### ISSUE THREAD

**Issue by hardixnph** [wisp-gg/frontend#59] opened 2022-02-13 17:08 UTC
**Describe the bug**
A strange 'scroll' I think

**To Reproduce**
1. Go to '/account'
2. Click on 'https://i.imgur.com/MGZaEDj.png'
3. See error

**Expected behavior**
To see the options without that strange scroll or whatever it is.

**Screenshots**
https://i.imgur.com/RcDX5qc.png

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 98.0.4758.82 (Official Build) (64-bit)

**Additional context**
It happens on 'Language' too

**Comment by WISPdotGG** [comment] 2022-02-13 17:10
Duplicate of #25

**Closed by WISPdotGG** 2022-02-13 17:10 UTC
