### ISSUE TITLE
Websocket permission error, but everything seems to work correctly

### ISSUE THREAD

**Issue by BeepSterr** [wisp-gg/frontend#9] opened 2022-02-13 15:11 UTC
**Describe the bug**
Sometimes when visiting a server page, A Banner will appear with a "Websocket permission" error.
This banner also appears when using a admin user, but not always.

**To Reproduce**
1. Click on to any server (front end or admin area)
2. have a chance at experience ![image](https://user-images.githubusercontent.com/1830450/153759489-bbe66361-983e-4b15-a9f0-e4a908118cc5.png)

**Expected behavior**
Shouldn't have websocket permission errors, as i'm logged in as admin

**Screenshots**
![image](https://user-images.githubusercontent.com/1830450/153759503-9436e228-7716-4639-b73d-74e8a9b1a56d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 98.0.1108.50
 - Extensions: uBlock origin (Only blocking ingest.sentry.io from looking at devtools)
 - 
**Additional context**
Could it be a issue with the deamons not being updated yet?

**Comment by WISPdotGG** [comment] 2022-02-13 16:14
Also seen this error when the update was first rolling out, but it went away, not sure on the cause

**Comment by WISPdotGG** [comment] 2022-02-13 16:36
Re-opening this issue because of more reports. Possibly related to daemon updates? Maybe daemon restart to try and fix it?

**Comment by WISPdotGG** [comment] 2022-02-13 16:40
Also reported by Discord user Ephrey#0001

**Comment by WISPdotGG** [comment] 2022-02-13 16:41
Apparently restarting the daemon fixed this issue for one user

**Comment by BeepSterr** [comment] 2022-02-13 17:05
Nothing interesting showing up in mine
```Attaching to wisp_bootstrapper_1
bootstrapper_1  | 2022-02-13T16:53:24.732Z [BOOTSTRAPPER] [INFO] Hello world!
bootstrapper_1  | 2022-02-13T16:53:24.801Z [BOOTSTRAPPER] [INFO] Running project daemon...
bootstrapper_1  | [DAEMON] 16:53:25.054Z  INFO wings: + ------------------------------------ +
bootstrapper_1  | [DAEMON] 16:53:25.056Z  INFO wings: |      Running WISP Daemon v2.0.0      |
bootstrapper_1  | [DAEMON] 16:53:25.056Z  INFO wings: |           https://wisp.gg/           |
bootstrapper_1  | [DAEMON] 16:53:25.056Z  INFO wings: + ------------------------------------ +
bootstrapper_1  | [DAEMON] 16:53:25.062Z  INFO wings: Verifying state of certificates...
bootstrapper_1  | [DAEMON] 16:53:25.099Z  INFO wings: Loading modules, this could take a few seconds.
bootstrapper_1  | [DAEMON] 16:53:25.951Z  INFO wings: Modules loaded, starting WISP Daemon...
bootstrapper_1  | [DAEMON] 16:53:25.992Z  INFO wings: Configuring user wisp (id: 999) as the owner of all server files.
bootstrapper_1  | [DAEMON] 16:53:25.999Z  INFO wings: Configuring timezone file location...
bootstrapper_1  | [DAEMON] 16:53:25.999Z  INFO wings: Checking container networking environment...
bootstrapper_1  | [DAEMON] 16:53:26.001Z  INFO wings: Found network interface for daemon: wisp_nw
bootstrapper_1  | [DAEMON] 16:53:26.001Z  INFO wings: Ensuring correct network interface for containers...
bootstrapper_1  | [DAEMON] 16:53:26.006Z  INFO wings: Networking gateway detected as 172.200.0.1 for interface: wisp0.
bootstrapper_1  | [DAEMON] 16:53:26.009Z  INFO wings: Contacting panel to retrieve a list of currrent Eggs available to the node.
bootstrapper_1  | [DAEMON] 16:53:26.214Z  INFO wings: Checking existing eggs against Panel response...
bootstrapper_1  | [DAEMON] 16:53:26.227Z  INFO wings: Beginning server initialization process.
bootstrapper_1  | [DAEMON] 16:53:26.254Z  INFO wings: Server status has been changed to ON (server=97c042ea-9f56-41cb-b8b5-e739391df952)
bootstrapper_1  | [DAEMON] 16:53:26.266Z  INFO wings: Server status has been changed to ON (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 16:53:26.273Z  INFO wings: Daemon detected that the server container is currently running, re-attaching to it now! (server=97c042ea-9f56-41cb-b8b5-e739391df952)
bootstrapper_1  | [DAEMON] 16:53:26.278Z  INFO wings: Daemon detected that the server container is currently running, re-attaching to it now! (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 16:53:26.283Z  INFO wings: Configuring websocket for daemon stats...
bootstrapper_1  | [DAEMON] 16:53:26.287Z  INFO wings: WISP Daemon is now listening for secure connections on 0.0.0.0:8080
bootstrapper_1  | 2022-02-13T16:53:26.287Z [BOOTSTRAPPER] [INFO] Project daemon is now running.
bootstrapper_1  | 2022-02-13T16:53:26.288Z [BOOTSTRAPPER] [INFO] Running project sftp-server...
bootstrapper_1  | [SFTP-SERVER] 1.6447712062925682e+09  info    sftp-server/main.go:47  reading configuration from path {"config-path": "../daemon/config/wisp.yaml"}
bootstrapper_1  | [SFTP-SERVER] 1.644771206292767e+09   info    sftp-server/main.go:67  using system daemon user        {"username": "wisp"}
bootstrapper_1  | [SFTP-SERVER] 1.6447712062931647e+09  info    sftp-server/main.go:80  using config daemon port        {"port": 2022}
bootstrapper_1  | [SFTP-SERVER] 1.6447712063001091e+09  info    server/server.go:105    server listener registered      {"address": "[::]:2022"}
bootstrapper_1  | 2022-02-13T16:53:26.300Z [BOOTSTRAPPER] [INFO] Project sftp-server is now running.
bootstrapper_1  | [DAEMON] 16:53:28.267Z  WARN wings: Failed running a game query: query errored for minecraft @ 209.250.244.48:25565 - Error: Failed all 1 attempts (server=97c042ea-9f56-41cb-b8b5-e739391df952)
bootstrapper_1  | [DAEMON] 16:53:28.269Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 16:53:33.256Z  WARN wings: Failed running a game query: query errored for minecraft @ 209.250.244.48:25565 - Error: Failed all 1 attempts (server=97c042ea-9f56-41cb-b8b5-e739391df952)
bootstrapper_1  | [DAEMON] 16:53:33.268Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 16:53:38.256Z  WARN wings: Failed running a game query: query errored for minecraft @ 209.250.244.48:25565 - Error: Failed all 1 attempts (server=97c042ea-9f56-41cb-b8b5-e739391df952)
bootstrapper_1  | [DAEMON] 16:53:38.257Z  WARN wings: Omitting any failed game query messages until query succeeds or server gets restarted. (server=97c042ea-9f56-41cb-b8b5-e739391df952)
bootstrapper_1  | [DAEMON] 16:53:38.269Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 16:53:38.269Z  WARN wings: Omitting any failed game query messages until query succeeds or server gets restarted. (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:17.467Z  INFO wings: Server status has been changed to STOPPING (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:17.475Z  INFO wings: Server status has been changed to OFF (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:18.283Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:26.918Z  INFO wings: Server status has been changed to STARTING (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:51.735Z  INFO wings: Server status has been changed to ON (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:53.737Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:53.917Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:02:53.917Z  WARN wings: Omitting any failed game query messages until query succeeds or server gets restarted. (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:03:30.800Z  INFO wings: Server status has been changed to OFF (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:03:31.099Z  WARN wings: Server detected as crashed! Attempting server reboot. (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17, ExitCode=0, OOMKilled=false, Error="")
bootstrapper_1  | [DAEMON] 17:03:31.100Z  INFO wings: Server status has been changed to STARTING (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:03:31.734Z  INFO wings: Notified remote panel of server action log.
bootstrapper_1  | [DAEMON] 17:03:50.485Z  INFO wings: Server status has been changed to ON (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:03:52.487Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:03:53.102Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:03:58.103Z  WARN wings: Failed running a game query: query errored for minecraft @ 172.200.0.1:5000 - Error: Failed all 1 attempts (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
bootstrapper_1  | [DAEMON] 17:03:58.103Z  WARN wings: Omitting any failed game query messages until query succeeds or server gets restarted. (server=46063bc9-4d29-4247-9aa6-b8c9841d2a17)
```

**Comment by TrixterTheTux** [comment] 2022-02-13 18:07
Are you admin or a normal user(/subuser)? Does `wisp restart` fix it?

**Comment by AnthonyLF** [comment] 2022-02-13 18:16
Wisp restart changes absolutely nothing :(

**Comment by hoshic** [comment] 2022-02-13 18:17
Same issue, restarting doesent fix anything, only reloading the page does but when switiching the pages its there again.
There are no logs about it

**Comment by TrixterTheTux** [comment] 2022-02-13 19:15
Could you run `wisp restart` and check if this happens now?

**Comment by hoshic** [comment] 2022-02-13 19:31
https://gyazo.com/6659535bb188c259b3aa5d5283521ed9
https://gyazo.com/e6380be86f0ade41a8e0362b6519b93c

(2 gifs about it)

**Comment by WISPdotGG** [comment] 2022-02-13 21:52
Just got this, screenshot with console. Happened when I was routed to the AU pop.
![image](https://user-images.githubusercontent.com/72014066/153776655-d87dead6-5234-4edd-9d4a-ba44e9f54ca9.png)

**Comment by desperadisse** [comment] 2022-02-13 22:21
Same error after reboot

**Comment by quantumdevuk** [comment] 2022-02-13 23:09
i have the same error, tried refreshing ext

**Comment by TrixterTheTux** [comment] 2022-02-14 20:40
When you're on the server list page - what does the status indicator say for the server?

**Comment by Stodgems** [comment] 2022-02-15 12:31
The first 3 lots say online the rest say error, and the same 3 slots on the following pages say online but error for the rest just like the first page.

**Comment by WISPdotGG** [comment] 2022-02-15 21:29
These steps reproduce the issue. Sending here just for record-keeping/searchability sake:
https://user-images.githubusercontent.com/72014066/154152285-d3fef1b8-a945-4b8d-bd37-20899f2eb5f1.mp4

Steps:
1 Refresh
2 Click a server (quickly?)
3 Click the dog (quickly?)
4 Click another server (quickly?)

**Comment by Stodgems** [comment] 2022-02-16 21:45
I got this error but I dont know if this is because of the change you did which is probs still doings its thing, 
![image](https://user-images.githubusercontent.com/60156251/154362488-2aedad19-0421-440f-8c74-043ac6b19149.png)

**Comment by Stodgems** [comment] 2022-02-16 21:46
I have also restarted wisp before and this message showed up after I restarted

**Comment by victiondev** [comment] 2022-02-16 21:49
what daemon version does it say your node is running on in the about tab of the node settings?

**Comment by Stodgems** [comment] 2022-02-16 21:50
Daemon v2.0.1

**Comment by victiondev** [comment] 2022-02-16 22:46
you seem to be on the beta branch if you weren't updated - I just pushed the update to the beta branch, can you check again?

**Comment by Stodgems** [comment] 2022-02-16 22:48
It works now thanks!

**Comment by victiondev** [comment] 2022-02-16 23:51
Just pushed another update which addresses a separate issue for websocket perms, which caused invalid (at the time) tokens to be cached and thus had no perms when they became valid (post server install)

**Comment by victiondev** [comment] 2022-02-18 17:53
This seems to be fixed now so closing, feel free to open another issue if you get this issue again (and the server isnt suspended)

**Closed by victiondev** 2022-02-18 17:54 UTC
Labels: bug, high, not confirmed
