### ISSUE TITLE
Databse host displays generic error.

### ISSUE THREAD

**Issue by BeepSterr** [wisp-gg/frontend#180] opened 2022-02-20 10:16 UTC
**Describe the bug**
The database server create modal shows a useless generic error banner on the page behind it when attempting to add a database
server with invalid settings.

**To Reproduce**
1. Add a database server with a hostname instead of IP
2. Get a non-descriptive error in the background

**Expected behavior**
Display the proper error, And update the label since FQDM's are not allowed.
Make FQDM's actually allowed

**Screenshots**
![image](https://user-images.githubusercontent.com/1830450/154837909-ba2d5e44-78df-4e17-8045-c89cba2d8fa2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19044
 - Browser Edge 98.0.11

**Comment by TrixterTheTux** [comment] 2022-02-20 10:19
Duplicate of #109

**Closed by TrixterTheTux** 2022-02-20 10:19 UTC
