### ISSUE TITLE
Support OP Bypass SFTP

### ISSUE THREAD

**Issue by SkyMulley** [wisp-gg/frontend#173] opened 2022-02-17 05:32 UTC
**Describe the bug**
When Support OP Bypass is enabled, the SFTP tab on services that they are not subusers on is viewable (even though they cannot connect)

**To Reproduce**
1. Enable Support Op Bypass for a user
2. Login with that user and attempt to view any service they are not a sub-user of
3. SFTP Details tab is viewable and supplies details, even though they are not valid

**Expected behavior**
SFTP tab shouldn't be viewable, and instead show permission denied like the databases and subusers tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/22577275/154411764-39529bac-1054-49c2-9611-63bdbf722ed2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: Latest Stable

**Comment by TrixterTheTux** [comment] 2022-02-20 13:07
Unable to reproduce - support OPs do have permission to access SFTP.

**Comment by SkyMulley** [comment] 2022-02-20 15:26
I'm continuing to get "Access Denied" errors while attempting to access SFTP for servers that I have support op access to. This is occurring across multiple instances of WISP and multiple daemons.

**Comment by TrixterTheTux** [comment] 2022-02-20 17:53
Found the issue, should be fixed in the next release.

**Closed by TrixterTheTux** 2022-02-20 17:53 UTC
Labels: bug, UI, low
