### ISSUE TITLE
IP field in the New Allocation form look weird

### ISSUE THREAD

**Issue by brandonsturgeon** [wisp-gg/frontend#325] opened 2022-09-06 22:09 UTC
### Describe the bug

The dropdown covers up the text entry, making it look kind of weird.

![image](https://user-images.githubusercontent.com/7936439/188749031-956cbbf8-97aa-4ae6-81df-7dbd007225fc.png)

### Expected Behavior

The text entered in the input field should be visible while typing it.

**or**

The entry field should contain no cursor or text-partials, having it (and a text-cursor) only appear in the dropdown menu before you select it.

### Actual Behavior

The input field is covered up by the auto-fill dropdown.

### Steps to Reproduce

 - Create a new Allocation
 - Type in the IP field

### Browser Details

104.0.1 (64-bit)

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment] 2022-09-07 07:23
Duplicate of #136

**Closed by TrixterTheTux** 2022-09-07 07:23 UTC
Labels: bug
