### ISSUE TITLE
Readd node allocation statistics

### ISSUE THREAD

**Issue by bgbuddyboy** [wisp-gg/frontend#113] opened 2022-02-14 05:46 UTC
**This is purely for frontend-related feature requests - requests like subdomain manager, etc. are currently better suited for our [Discord](https://wisp.gg/discord) instead.**

**Is your feature request related to a problem? Please describe.**
Readd node allocation statistics when viewing node, with graph like v1

**Describe the solution you'd like**
Feature added back like v2

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by WISPdotGG** [comment] 2022-02-14 09:55
V1 didn't have a graph for node allocation statistics as far as I'm aware? Are you referring to the statistics page on the admin area? If so check #92

**Comment by bgbuddyboy** [comment] 2022-02-14 10:38
Allocation is used a lot in the panel, I mean the resource allocation not the IP allocation.
V1 had a progress bar like graph and colours depicting the percentage used

**Comment by Larsdeijsbeer** [comment] 2022-02-15 20:53
@bgbuddyboy is talking about the resource allocation information at the node About page. 

![nodeallocationwisp](https://user-images.githubusercontent.com/27996312/154147160-a90d7ec0-9818-45ef-827b-406744fbf99d.png)

**Comment by JouanDeag** [comment] 2022-02-19 17:31
Duplicate of #91

**Closed** 2022-02-19 17:31 UTC
Labels: not confirmed
