### ISSUE TITLE
Server-list pages not working

### ISSUE THREAD

**Issue by ThePlay3r** [wisp-gg/frontend#3] opened 2022-02-13 15:06 UTC
**Describe the bug**
As title says, when trying to switch to another serverlist page, it doesn't work.

**To Reproduce**
1. Go to 'Main Page/Server List'
2. Click on 'For example seconds page/page change button.'
3. Nothing happens. (Site refreshes, same page)

**Expected behavior**
I expect to see other/next page of servers.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 98.0b3

**Comment by WISPdotGG** [comment] 2022-02-13 15:33
Mistake, not a duplicate of this issue

**Comment by TrixterTheTux** [comment] 2022-02-13 16:50
Should be fixed in next release.

**Closed by TrixterTheTux** 2022-02-13 16:50 UTC
Labels: bug, UI, medium
