### ISSUE TITLE
server installation page

### ISSUE THREAD

**Issue by hoshic** [wisp-gg/frontend#89] opened 2022-02-13 19:58 UTC
**Describe the bug**
The installing server installing message / page most of the times doesent get shown.

https://gyazo.com/5e0e340d60b69634cf9da14185852b40

**To Reproduce**
Install a server that takes some time to install like a source game server.
And then click on it / try to manage it while instsalling

**Comment by krenny** [comment] 2022-02-13 20:05
![image](https://user-images.githubusercontent.com/77990771/153772700-ade0580c-9558-4034-b374-0b08f03baa3d.png)

**Comment by JouanDeag** [comment] 2022-02-13 21:07
Reproduced

**Comment by glitchxst** [comment] 2022-02-17 09:01
Reproduced - same thing on my end

**Comment by victiondev** [comment] 2022-02-20 23:03
Pretty sure this has been since fixed in a previous release, this happened because the state pages were not enforced until you tried interacting with the server.

**Closed by victiondev** 2022-02-20 23:03 UTC
Labels: bug, UI, medium
