### ISSUE TITLE
Cannot delete Processing Schedule

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/frontend#203] opened 2022-02-24 13:50 UTC
### Describe the bug

When a schedule is triggered it can't be deleted. 

### Expected Behavior

Be able to delete a schedule when processing.

### Actual Behavior

It can't be deleted while processing.

### Steps to Reproduce

![cannotdeleteschedule](https://user-images.githubusercontent.com/27996312/155536488-68714ebb-d048-4112-998b-a542ab0aded9.gif)

1. Trigger a schedule which creates a backup
2. Try to delete the schedule

### Browser Details

Chrome 98.0.4758.102 

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment] 2022-02-25 10:49
Unable to reproduce this locally and in prod environment.

**Comment by TrixterTheTux** [comment] 2022-02-26 16:48
Deletion worked for me :v

**Comment by TrixterTheTux** [comment] 2022-03-26 19:59
Closing due to not being able to reproduce.

**Closed by TrixterTheTux** 2022-03-26 19:59 UTC
Labels: bug, medium
