### ISSUE TITLE
Notifications UI being small

### ISSUE THREAD

**Issue by WISPdotGG** [wisp-gg/frontend#148] opened 2022-02-15 15:57 UTC
**Describe the bug**
Notification UI is small, unusable

**To Reproduce**
1. Open notification tray

**Expected behavior**
Normal size tray which can be read

**Screenshots**
![image](https://user-images.githubusercontent.com/72014066/154099160-ae586917-8523-41a9-b68d-219a76ebb55a.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge
 - Version unknown

**Additional context**
Opened on behalf of lucaiscool#1234

**Comment by DarthShmev** [comment] 2022-02-15 15:58
Can’t reproduce either on Chrome.

**Comment by larsjarred9** [comment] 2022-02-15 16:03
Can't reproduce on Opera

**Comment by TrixterTheTux** [comment] 2022-02-20 12:28
I suspect this is due to the notification's body being empty - most likely already fixed (and as no one else can reproduce not much to investigate), closing.

**Closed by TrixterTheTux** 2022-02-20 12:28 UTC
Labels: not confirmed
