### ISSUE TITLE
Quick view client's server view from admin side

### ISSUE THREAD

**Issue by rowansc1** [wisp-gg/frontend#132] opened 2022-02-14 23:24 UTC
**Is your feature request related to a problem? Please describe.**
Accessibility to quickly view the client's side of a server

**Describe the solution you'd like**
Please have the feature where you can quickly access the client's side of a server via a button like before. 

**Describe alternatives you've considered**
Going into the overview and finding the server there. 

**Additional context**
Originally the button was here:
![SyC6W4wlKz1RYdPOKD9mIatmgneuzE](https://user-images.githubusercontent.com/37227235/153963719-7e773b62-7d72-4052-9d3d-1932b8c2e6dc.png)

**Comment by TrixterTheTux** [comment] 2022-02-15 06:19
Duplicate of #39, should be fixed in next release.

**Closed by TrixterTheTux** 2022-02-15 06:19 UTC
