### ISSUE TITLE
Search bar for various pages not appearing on admin end

### ISSUE THREAD

**Issue by Larkify** [wisp-gg/frontend#55] opened 2022-02-13 17:01 UTC
**Describe the bug**
Before v2, there was a search bar on the users, servers etc page on the admin end. That doesn't appear to exist anymore.

**To Reproduce**
1. Go to the admin end
2. Click on servers or users 

**Expected behavior**
A search bar should appear at the top allowing admin users to query through all users/servers etc.

**Screenshots**
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/69719309/153765935-9ddde504-620b-4e1b-a4ca-30d257b7737b.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Safari
 - Version: v2.0.11

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15
 - Browser Safari
 - Version v2.0.11

**Additional context**

**Comment by bastienroussel** [comment] 2022-02-13 17:15
Duplicate of #20

**Comment by Larkify** [comment] 2022-02-13 17:57
> Duplicate of #20

No, that issue is about the search bar on the user end, not the admin end.

**Closed** 2022-02-14 08:29 UTC
Labels: UI, high, missing
