### ISSUE TITLE
Ability to schedule git pull

### ISSUE THREAD

**Issue by 0xCiBeR** [wisp-gg/frontend#337] opened 2022-10-04 13:29 UTC
### Describe the feature and why you would like to see it.

Clients would very much benefit in a way to automaticly pull a repository without having to do this manually.

### Describe the solution you'd like.

I thought of 2 ways this could be done, each with pros and cons:
- Allow git pulls to be scheduled in the schedules system
- Create a unique webhook where we can remotly trigger the pull(this would be util for setting up pipelines on the git repo, where a change triggers a pipeline that will then call a webhook url making the panel pull the new code)

**Comment by TrixterTheTux** [comment] 2022-10-04 13:33
Duplicate of #324

**Closed by TrixterTheTux** 2022-10-04 13:33 UTC
