### ISSUE TITLE
Problem with update

### ISSUE THREAD

**Issue by Indygen** [wisp-gg/frontend#35] opened 2022-02-13 15:50 UTC
After the update, the SFTP did not work anymore, I restarted the wisp and when it started I received the following error:

**To Reproduce**
I gave the "wisp tail" command in the console to check what was wrong, it wrote to me that it can't update to sftp, after which I gave the "wisp restart" command and from there I get the above error and I can't access anything.

**Expected behavior**
I expected that after the restart, the sftp server would update and everything would work normally.

https://termbin.com/rl9z
https://imgur.com/a/YdJ21tJ

**Comment by WISPdotGG** [comment] 2022-02-13 15:54
Duplicate of #13

**Closed by WISPdotGG** 2022-02-13 15:54 UTC
