### ISSUE TITLE
api/application/servers POST request 

### ISSUE THREAD

**Issue by ianleckey** [wisp-gg/frontend#50] opened 2022-02-13 16:45 UTC
```
curl "<panelurl>/api/application/servers" \
  -H "Authorization: Bearer <token>" \
  -H "Content-Type: application/json" \
  -H "Accept: Application/vnd.pterodactyl.v1+json" \
  -X POST \
  -d '{
    "name": "test",
    "user": 65,
    "egg": 14,
    "docker_image": "quay.io/wisp/images:java",
    "startup": "java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}",
    "environment": {
      "SERVER_JARFILE": "server.jar",
      "VANILLA_VERSION": "latest"
    },
    "limits": {
    "memory": 1024,
      "swap": -1,
      "disk": 10240,
      "io": 500,
      "cpu": 100
    },
    "feature_limits": {
      "databases": 1,
      "allocations": 1
    },
    "deploy": {
      "locations": [],
      "dedicated_ip": false,
      "port_range": []
    }
  }'
```

Returns:
```
{
    "errors": [
        {
            "code": "TypeError",
            "status": "500",
            "detail": "An error was encountered while processing this request."
        }
    ]
}
```

**Comment by WISPdotGG** [comment] 2022-02-13 16:46
I think this is a duplicate of #6

**Closed by WISPdotGG** 2022-02-13 16:46 UTC
