### ISSUE TITLE
Egg Installs Not Working

### ISSUE THREAD

**Issue by arty01238** [wisp-gg/frontend#96] opened 2022-02-13 20:41 UTC
**Describe the bug**
Egg installs do not work, I went into the panel to reinstall a server and it says error occurred when trying to perform this action

**To Reproduce**
1. Go to 'Server'
2. Click on 'Configuration'
3. Click 'Advanced'
4. Choose Version Info
5. Hit install
6. Error

**Expected behavior**
I wanted to reinstall minecraft server

**Screenshots**
![image](https://user-images.githubusercontent.com/71173411/153774090-c598d427-992d-4a69-9900-e5d0324b4479.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser "Chrome"
 - Version "Dont Know"

**Smartphone (please complete the following information):**

**Additional context**

**Comment by krenny** [comment] 2022-02-13 20:46
This is not an egg install this is a minecraft version manager install please change the title.

Also I think that's a duplicate of an existing issue.....

**Comment by WISPdotGG** [comment] 2022-02-13 20:49
Duplicate of #23

**Closed by WISPdotGG** 2022-02-13 20:49 UTC
