### ISSUE TITLE
Clearing a date/time field when creating a schedule destroys the whole modal

### ISSUE THREAD

**Issue by notjoshmiles** [wisp-gg/frontend#36] opened 2022-02-13 15:52 UTC
**Describe the bug**
If you clear one of the fields in the create schedule modal...

![image](https://user-images.githubusercontent.com/19347018/153761169-0208d08e-6361-4896-9934-ce871c43091e.png)

It'll mess up the whole modal:

![image](https://user-images.githubusercontent.com/19347018/153761209-1f854da9-e02d-4d78-bb7b-0c72b275d61c.png)

**To Reproduce**
Go to the Schedules page for a server and try clearing one of the date/time fields

**Expected behavior**
The entire modal shouldn't be destroyed

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 98.0.4758.82

**Comment by WISPdotGG** [comment] 2022-02-13 15:57
Duplicate of #29

**Closed by WISPdotGG** 2022-02-13 15:57 UTC
