### ISSUE TITLE
All servers showing as offline in admin area

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#40] opened 2022-02-13 16:10 UTC
**Describe the bug**
All servers showing as offline in admin area

**To Reproduce**
1. Go to Admin area
2. Click on Management -> Servers
3. See error

**Expected behavior**
I expect to be able to see the status of servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/61161558/153761927-db9af49f-4eb3-4d44-9250-c82e159161f2.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome
Version: 98.0.4758.82

**Comment by WISPdotGG** [comment] 2022-02-13 16:12
I think this is a duplicate of this issue #18

**Closed by WISPdotGG** 2022-02-13 16:12 UTC
