### ISSUE TITLE
Page becomes blank after inactivity

### ISSUE THREAD

**Issue by lerndmina** [wisp-gg/frontend#84] opened 2022-02-13 19:22 UTC
**Describe the bug**
If viewing the console of a server and you re-open the tab after having it not focused for a while the page appears blank

**To Reproduce**
1. Go to the panel
2. Click on any server
3. Open a new tab
4. Browse for a while
5. Come back to the panel tab
6. Page appears blank and needs to be refreshed to repopulate

**Expected behavior**
The page should still be loaded

**Screenshots**
![Screenshot of blank page. Idk what you want from me XD](https://user-images.githubusercontent.com/10632157/153771160-9e935208-70fc-4bb2-9245-459451dccfd4.png)

**Desktop (please complete the following information):**
 - OS: `Win10`
 - Browser: `Edge, Chrome`
 - Version: `Chrome 98.0.4758.82 (Official Build) (64-bit)`
 - Wisp Version: `fr-gra-web01 - v2.0.19`

**Additional context**

**Comment by lerndmina** [comment] 2022-02-13 19:23
It also seems that when this happens, refreshing with CTRL+F5 is slower than usual.

**Comment by JouanDeag** [comment] 2022-02-13 19:26
Close/Duplicate of #82

**Comment by TrixterTheTux** [comment] 2022-02-20 18:18
Duplicate of/Caused by #124

**Closed by TrixterTheTux** 2022-02-20 18:18 UTC
Labels: not confirmed
