### ISSUE TITLE
Manage server button missing (redirect to the server console directly)

### ISSUE THREAD

**Issue by hoshic** [wisp-gg/frontend#48] opened 2022-02-13 16:39 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'a server in the admin area

**Expected behavior**
There should be a button in the admin area that redirects to the server aswell

**Screenshots**
https://gyazo.com/5b9f6c73123d32543893deaec1acf3d8

**Comment by WISPdotGG** [comment] 2022-02-13 16:43
Duplicate of #39

**Closed by WISPdotGG** 2022-02-13 16:43 UTC
